### ISSUE TITLE
ocr_api problem

### ISSUE THREAD

**Issue by xwater8** [winter2897/Real-time-Auto-License-Plate-Recognition-with-Jetson-Nano#1]
Hi,
 It's a great work. I have not run your code, I just read. I have some problem about ocr_api() in az_plate_api.py. What's the model in this API? Is this your az_ocr model or other website's API?
In your detection-camera.py, I can't see the ocr recognition part. Do you just split it into two parts?
Step1: detection plates from the video and save plate images.
Step2: OCR plates from plate images and save results.

**Comment by winter2897** [comment]
Thank you for your interest in the project. I have removed ocr_api () in az_plate_api.py. My project is developed in two steps just like you described. However, I have not yet finished pairing the two modules together.
