### ISSUE TITLE
Exception: jetson.inference -- detectNet failed to load network

### ISSUE THREAD

**Issue by hphuc4244** [winter2897/Real-time-Auto-License-Plate-Recognition-with-Jetson-Nano#3]
![image](https://user-images.githubusercontent.com/39155046/115332473-17cd7400-a1c2-11eb-8564-e406b0b4ba83.png)

**Comment by winter2897** [comment]
Hi @hphuc4244,

Bạn check lại phiên bản Tensor RT và Jetpack mà bạn cài đặt nhé. Hiện tại Nvidia đã cập nhật bản Jetpack mới và mình chưa test lại với bản mới này.

**Comment by mplaxman** [comment]
![Screenshot from 2021-12-01 20-12-49](https://user-images.githubusercontent.com/77098650/144262497-1b0fb499-788d-448e-97e9-af4ed359dfa3.png)
Hi we done all setup. other programs executing properly. this one only we are getting error like above.our tensorRT version 5.1.6-1+cuda10.0 . which version this existing model file required please help me.
